output_dir: runs/qwen3-vl-flowers
num_train_epochs: 1.0
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
weight_decay: 0.0
warmup_ratio: 0.03
logging_steps: 10
save_steps: 200
save_total_limit: 2
dataloader_num_workers: 0
push_to_hub: false
hub_model_id: null
evaluation_strategy: steps
report_to: none
precision:
  bf16: false
  fp16: false
